### PR TITLE
Print page fix

### LINKED ISSUE #1439: JS error on info/error pages
### Expected behaviour
No errors in console

### Actual behaviour
```
main.js:11132 Uncaught TypeError: Cannot read property 'setAttribute' of null
    at t.value (main.js:11132)
    at new t (main.js:11116)
    at main.js:11231
    at main.js:7371
    at Array.forEach (<anonymous>)
    at HTMLDocument.t (main.js:7370)
```

### Steps to reproduce the behaviour
Go to /session with an expired token
Go to /session with no token
Go to /session with an invalid token
Go to /
Try to complete another survey before completing one that has already been started

### LINKED ISSUE #1474: Print this page link does not show print
### Expected behaviour
Must display the print preview allowing the respondent to print the page

### Actual behaviour
Does not do anything and displays `Uncaught TypeError: Cannot read property 'setAttribute' of null`
Please find the attached screen shot

### Steps to reproduce the behaviour
Launch any business survey
Complete the survey 
and submit
Click view answers 
and click `Print this page`

### Technical information
Pre-prod
### Screenshot
screen shot 2018-02-26 at 10 22 06

### PR DESCRIPTION
**Pull request by nealedj**
### What is the context of this PR?
Removes an inline `onclick` attribute used for printing which is blocked by CSP. Moves print logic to separate print script.

Also fixes a JS error when loading any non-form page.

Fixes #1474 
Fixes #1439 

### How to review 
Complete a questionnaire that allows answers to be viewed after submission and click "Print page"

### CODE REVIEW

File: app/assets/js/app/modules/print.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+import domready from './domready'
+
+domready(() => {
+  Array.from(document.getElementsByClassName('btn-print'))
+    .forEach(el => el.addEventListener('click', () => window.print()))
+})
```
Comment (jonnyshaw89) [inline app/assets/js/app/modules/print.js:6]: Is this something that also needs to make its way into the pattern library?

Comment (nealedj) [reply app/assets/js/app/modules/print.js:6]: I'd guess that it wouldn't provide much value to standardise this sort of trivial script.

@saedwards @bennpearson what do you think?

**Review by jonnyshaw89 — APPROVED** [review]

**Review by dwyeradam — APPROVED** [review]
