### PR TITLE
Fix remove person with JS disabled

### LINKED ISSUE #889: Census: Household Composition: JS Disabled Cannot Remove Person
### Expected behaviour
When JS is disabled I can still remove people

### Actual behaviour
When JS is disable I cannot remove a person

### Steps to reproduce the behaviour
- Disable JS (e.g. Chrome->Settings->Advanced->Content Settings->Do not allow any site to run JS)
- Navigate to Household Composition
- Add 3 people
- Try and remove Person 2
- Observe the link (Remove) does nothing

#### Browser
Chrome or Lynx (Terminal)

#### Operating System
Windows / macOS Sierra

### Screenshot
image

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
Fixes https://github.com/ONSdigital/eq-survey-runner/issues/889
Also adds assertions to functional tests to actually test functionality

Test with and without JS to ensure that functionality fixes issue

### CODE REVIEW

**Review by hamishtaplin — COMMENTED** [review]
I think a simpler solution would be to swap the `type` attribute of the remove buttons to `button` at runtime so they don't submit the form when enter is pressed but will still work when interacted with by the user. This is consistent with how the 'add person' button works currently.

**Comment by jonnyshaw89** [comment]
@hamishtaplin Yes that is a lot simpler! 👍

File: app/assets/js/app/modules/household.js [hunk 1]
```diff
@@ -30,9 +30,9 @@ class HouseholdMember extends EventEmitter {
       }
     }
 
-    this.inputs = this.node.querySelectorAll('input')
+    this.inputs = this.node.querySelectorAll('.js-btn-remove')
```
Comment (hamishtaplin) [inline app/assets/js/app/modules/household.js]: `this.inputs` is used elsewhere, this will break it.

in the `bindToExisting` method, there's already a reference to the removeBtn—just do the attribute thing there

**Review by hamishtaplin — CHANGES_REQUESTED** [review]

File: app/templates/partials/questions/repeatinganswer.html [hunk 2]
```diff
@@ -20,7 +20,7 @@ <h3 class="neptune">{{ _('Person ') }}<span class="js-household-loopindex">{{ lo
           {%- if loop.index == 1 -%}
              <span class="js-household-action">{{ _('You') }}</span>
           {%- else -%}
-            <button class="btn btn--link pluto js-btn-remove" name="action[remove_answer]" value="{{ loop.index0 }}" type="button">{{ _('Remove') }}
+            <button class="btn btn--link pluto js-btn-remove" name="action[remove_answer]" value="{{ loop.index0 }}" type="submit">{{ _('Remove') }}
```
Comment (samiwel) [inline app/templates/partials/questions/repeatinganswer.html:21]: For non-JS enabled browsers, this is what was causing people (specifically Person 2) to be removed when users press ENTER key. So just to be aware that the defect will be re-introduced for non-JS browsers with this change.

Comment (samiwel) [reply app/templates/partials/questions/repeatinganswer.html:21]: But I understand that without this change you can't remove people for non-JS - which is probably more important.

Comment (jonnyshaw89) [reply app/templates/partials/questions/repeatinganswer.html:21]: @samiwel When i test this with javascript enabled it navigates me to the next page on pressing enter.

**Comment by jonnyshaw89** [comment]
@samiwel @hamishtaplin Ready for review.

File: app/templates/partials/questions/repeatinganswer.html (hunk 2 above)
Comment (hamishtaplin) [reply app/templates/partials/questions/repeatinganswer.html:21]: @samiwel @jonnyshaw89 I believe the non-js version should stick to the browser defaults (ie. the first button with `type=submit` submits the form when 'enter' is pressed). with JS, we remove that attribute and handle those actions only on click—meaning the browser will do exactly as the DOM describes.

**Review by samiwel — APPROVED** [review]

File: app/templates/questionnaire.html [hunk 3]
```diff
@@ -63,7 +63,7 @@ <h1 class="panel__title venus">This page has {{all_errors|length}} errors</h1>
     {% endif %}
 
     <form action="{{form_action|default('')}}" class="form qa-questionnaire-form" role="form" method="POST" novalidate>
-
+      <input type="submit" style="display: none" name="action[save_continue]" />
```
Comment (hamishtaplin) [inline app/templates/questionnaire.html]: I don't think we should be introducing this, especially to all questionnaires.

The non-js version (which nobody will use) behaves exactly as it's supposed to, this adds the risk of unwanted side-effects.

**Review by hamishtaplin — CHANGES_REQUESTED** [review]

File: app/templates/questionnaire.html (hunk 3 above)
Comment (jonnyshaw89) [reply app/templates/questionnaire.html]: @hamishtaplin i have removed this now

**Review by hamishtaplin — APPROVED** [review]

File: tests/functional/capabilities.js [hunk 4]
```diff
@@ -13,6 +13,17 @@ export const chrome = {
   ...defaultCapabilities
 }
 
+export const chromeNoJS = {
```
Comment (hamishtaplin) [inline tests/functional/capabilities.js:16]: It's cleaner to do this:

```js
export const chromeNoJS = {
  ...chrome,
  name: 'Chrome (No JavaScript) 48 | OS X 10.11',
  chromeOptions: {
    prefs: {'profile.managed_default_content_settings.javascript': 2}
  }
}
```

**Review by hamishtaplin — CHANGES_REQUESTED** [review]

**Review by hamishtaplin — APPROVED** [review]
